### ISSUE TITLE
email-templates: detect if absolute path was passed as a template, and if so then use absolute path instead

### ISSUE THREAD

**Issue by niftylettuce** [niftylettuce/bug-bounties#1]
https://github.com/niftylettuce/email-templates/issues/320

**Comment by pke** [comment]
Should the same absolute path also be used for `juiceResources` or does this still have to be configured manually?

**Comment by niftylettuce** [comment]
@pke it should still be configured manually.  Nice work.  Please send me an email at niftylettuce@gmail.com to receive your payout.
