### ISSUE TITLE
lad: switch from "agenda" to "bull"

### ISSUE THREAD

**Issue by niftylettuce** [niftylettuce/bug-bounties#9]
@builtbyproxy started working on this https://github.com/ladjs/lad/issues/344 in his branch at https://github.com/builtbyproxy/lad/tree/feature/agenda-to-bull - you can get inspiration from his work there

- [ ] remove the file `agenda.js` and replace with `bull.js`
- [ ] update all instances of usage of agenda and jobs to use bull (redis)
- [ ] update ecosystem.json to use bull instead of agenda (protip: use [ripgrep](https://github.com/BurntSushi/ripgrep) package to search across entire project for all instances of the words "agenda" or "job")
- [ ] there may be other things you have to do

**Comment by builtbyproxy** [comment]
In regards to replacing the `agenda.js` with `bull.js` 
Agenda doesnt take `queue`s like Bull does. This gives us a heap of new possibilites however it makes replacing such a general file a bit more intense. Im looking forward to writing a handler to sort based on queue type or something similar though.

Additionally, From what I can see agenda is only used for two job types, emails and mandarin translating. Therefore we could use that as two queue types, emails and translation. Still looking into that though we can most likely make it even more generic.

Finally, email-preview is difficult to test with in my opinion. I have emails being scheduled in the redis server however nothing is triggered. I believe this is out of scope however so will work on getting something to log in the console on a schedule first and THEN implement email-previews.

Thoughts? @niftylettuce

**Comment by niftylettuce** [comment]
I've implemented Bull myself in the latest version of Lad `npm i -g lad`

Thanks to @builtbyproxy and @shaunwarman for their inspirational work.
